### ISSUE TITLE
Homepage driver to lbry.io

### ISSUE THREAD

**Issue by kauffj** [lbryio/lbry.tech#105]
lbry.tech should have a driver to lbry.io for those who end up on lbry.tech when they really wanted to be on lbry.io

My proposal is another callout on the homepage below the hero (in `<section class="features">`).

**Comment by NetOperatorWibby** [comment]
This floating button could possibly be annoying so I propose to have a close button. Does this make sense? If so, I would also make it float in the middle bottom of the screen, slightly above the beta message for aesthetic purposes.

**Comment by NetOperatorWibby** [comment]
Closed via https://github.com/lbryio/lbry.tech/commit/6f0542a78d1093471f43c86438d08cc7965536ac
