### ISSUE TITLE
Urgent Fix require Lbry.tech giving application error 

### ISSUE THREAD

**Issue by iamuditpatel** [lbryio/lbry.tech#107]
![lbry tech](https://user-images.githubusercontent.com/11346292/41496719-5f61c08c-7164-11e8-9c0b-0f564b4c7699.PNG)

when i check the site with VPN

it's giving 503 error

![vpn](https://user-images.githubusercontent.com/11346292/41496723-7041d6bc-7164-11e8-9c00-0d0d384b8912.PNG)

**Comment by tzarebczan** [comment]
The site is back up.
