### ISSUE TITLE
Broken link in footer need to be fix as soon as possible

### ISSUE THREAD

**Issue by iamuditpatel** [lbryio/lbry.tech#108]
I think there is a problem in this script

https://github.com/lbryio/lbry.tech/blob/master/content/.vuepress/components/EditLink.vue

below is the link with 404 error:

https://github.com/lbryio/lbry.tech/edit/master/community/
https://github.com/lbryio/lbry.tech/edit/master/build/
https://github.com/lbryio/lbry.tech/edit/master/contribute/
https://github.com/lbryio/lbry.tech/edit/master/resources/
https://github.com/lbryio/lbry.tech/edit/master/overview/

![lbry broken link](https://user-images.githubusercontent.com/11346292/41505525-816d4948-7228-11e8-8564-ba2a239485a4.PNG)
![broken link 2](https://user-images.githubusercontent.com/11346292/41505527-866ab84a-7228-11e8-9967-fd57faeb65c5.PNG)

**Comment by tzarebczan** [comment]
Please review prior issues before creating new ones, this is already filed : https://github.com/lbryio/lbry.tech/issues/90
