### ISSUE TITLE
Publishing test results

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry.tech#116]
Here's what I got during my first publish: https://www.screencast.com/t/hktjJX7i (worked 2nd /3rd time, see #5 below)

1) I thought someone is supposed to be able to upload their own image? I don't see that option. 

2) looks like it publishes using the title as the claim name - we need to either randomize this part after the name (set a max limit on characters to save on claim fees) or check if a name is already taken. You can only publish to 1 name per wallet, otherwise it just updates it (known limitation of the daemon right now). 

3) I didn't set NSFW for my 2nd publish, but it published as NSFW even though the curl example has false: . ``` (curl "http://localhost:5279" --data "{ 'method': 'publish', 'params': { 'name': 'test2', 'bid': 0.001, 'file_path': '/path/to/your/file.jpg', 'title': 'test2', 'description': 'Check out this image I published to LBRY via lbry.tech', 'language': 'en', 'license': 'Public Domain', 'nsfw': 'false' } }"```
This happens for all publishes. 

4) The explorer.lbry.io link should open in a new page. Also add a note that it may take a minute or two to show up there. 

5) not sure why the result is blank (I did it a 2nd/3rd time, and it came back with a result) 

6) We should show the resulting LBRY URL, ie. lbry://claimname#claimid. Also, we should add an open.lbry.io/<claimname>:<claimid> link and say "open with the LBRY app" - include download link  (lbry.io/get)if they don't have it

7) @kauffj should we include a spee.ch link too? 

8 ) I can't get the image I uploaded at: lbry://test2#73e9f24aa331c0e790202ca7b23e9cf98d635fed - maybe ports need to be opened or it just needs some time to reflect from our content hosts. Will try again later. I was able to download another one I published.

**Comment by kauffj** [comment]
(@NetOperatorWibby please consider this ticket to be to fix these issues and do any other clean up or improvements you want to do in the process. For anything here that you can't address entirely on lbry.tech side, just open the appropriate issue.)

**Comment by NetOperatorWibby** [comment]
Closed in favor of #133
