### ISSUE TITLE
"In dev" notification

### ISSUE THREAD

**Issue by Krisseck** [lbryio/lbry.tech#12]
Have a large notification or similar element to display that this website is still in active current development

**Comment by Krisseck** [comment]
This was removed in the redesign, do we still want it?

**Comment by kauffj** [comment]
Yes. @NetOperatorWibby can you incorporate this into the design? I'm planning / expecting to launch or at least begin leaking the site before all content is ready.

**Comment by NetOperatorWibby** [comment]
Absolutely
