### ISSUE TITLE
Need better 404 pages

### ISSUE THREAD

**Issue by maximest-pierre** [lbryio/lbry.tech#120]
![screenshot from 2018-07-09 10-13-44](https://user-images.githubusercontent.com/7928135/42455686-f1588db4-8360-11e8-97ee-b43453d47b22.png)
The lbry.tech website should have a better 404 page than just not found.

**Comment by NetOperatorWibby** [comment]
Closed via https://github.com/lbryio/lbry.tech/commit/ec5b2610e5c37e70a1020bd6229e4772d2ed0e7f
