### ISSUE TITLE
Finish switch from Vue/Vuepress to choo and fastify

### ISSUE THREAD

**Issue by kauffj** [lbryio/lbry.tech#121]
@NetOperatorWibby will fill in specific choices.

**Comment by NetOperatorWibby** [comment]
Branch is [here](https://github.com/lbryio/lbry.tech/tree/new)

**Comment by alyssaoc** [comment]
@NetOperatorWibby make grab latest posts.... its own issue

**Comment by alyssaoc** [comment]
@NetOperatorWibby Remove API documentation from this issue

**Comment by NetOperatorWibby** [comment]
Closed via https://github.com/lbryio/lbry.tech/commit/1e4224617daa0863d16f2692f83e91a4ab3fa9cd
