### ISSUE TITLE
add resource page for LBRY api wrappers

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry.tech#123]
Thought lbry.tech would be a good place to keep track of lbry/community maintained api wrappers. Currently we have the [php-api wrapper](https://github.com/lbryio/php-api) and [Ruby Gem](https://rubygems.org/gems/lbry) / [Ruby Github](https://github.com/dan1d/lbry-api-ruby)

**Comment by kauffj** [comment]
Definitely!

**Comment by alyssaoc** [comment]
This is a duplicate of #117  and will be closed

**Comment by tzarebczan** [comment]
completed in https://github.com/lbryio/lbry.tech/pull/137
