### ISSUE TITLE
iOS bounty link doesn't exist

### ISSUE THREAD

**Issue by NetOperatorWibby** [lbryio/lbry.tech#126]
The link (`https://lbry.io/bounty/ios-daemon`) can be found on the [Build page](https://github.com/lbryio/lbry.tech/blob/master/documents/build.md) but the page doesn't exist.

**Comment by tzarebczan** [comment]
@kauffj should we remove this reference based on Akinewale's latest work? Or is it still valid?

**Comment by kauffj** [comment]
Drop it
