### ISSUE TITLE
Reimagine Tour

### ISSUE THREAD

**Issue by NetOperatorWibby** [lbryio/lbry.tech#133]
The Tour can be done in a way that makes it more intuitive for visitors.

Tom's original comments:

> Here's what I got during my first publish: https://www.screencast.com/t/hktjJX7i (worked 2nd /3rd time, see #5 below)
>
> 1) I thought someone is supposed to be able to upload their own image? I don't see that option. 
>
> 2) looks like it publishes using the title as the claim name - we need to either randomize this part after the name (set a max limit on characters to save on claim fees) or check if a name is already taken. You can only publish to 1 name per wallet, otherwise it just updates it (known limitation of the daemon right now). 
>
> 3) I didn't set NSFW for my 2nd publish, but it published as NSFW even though the curl example has false: . ``` (curl "http://localhost:5279" --data "{ 'method': 'publish', 'params': { 'name': 'test2', 'bid': 0.001, 'file_path': '/path/to/your/file.jpg', 'title': 'test2', 'description': 'Check out this image I published to LBRY via lbry.tech', 'language': 'en', 'license': 'Public Domain', 'nsfw': 'false' } }"```
This happens for all publishes. 
>
> 4) The explorer.lbry.io link should open in a new page. Also add a note that it may take a minute or two to show up there. 
>
> 5) not sure why the result is blank (I did it a 2nd/3rd time, and it came back with a result) 
>
> 6) We should show the resulting LBRY URL, ie. lbry://claimname#claimid. Also, we should add an open.lbry.io/<claimname>:<claimid> link and say "open with the LBRY app" - include download link  (lbry.io/get)if they don't have it
>
> 7) @kauffj should we include a spee.ch link too? 
>
> 8 ) I can't get the image I uploaded at: lbry://test2#73e9f24aa331c0e790202ca7b23e9cf98d635fed - maybe ports need to be opened or it just needs some time to reflect from our content hosts. Will try again later. I was able to download another one I published.

**Comment by NetOperatorWibby** [comment]
Tom and I figured out where the `images.php` was and have no idea why it's not in a repo. It looks rushed and doesn't do everything I'd expect the web daemon to do outside of handle image uploads and show them to me.

Additionally, the meme uploader doesn't seem like a good candidate for the tour. If visitors have to wait _minutes_ for a notification stating their image is on the blockchain, I don't think they'll stick around.

**Comment by kauffj** [comment]
We should be looking at just a few seconds come daemon 0.30. Even on an earlier version you shouldn't see a wait time of minutes, though.

**Comment by NetOperatorWibby** [comment]
Ah okay. I was basing this on convos about speech uploads from mobile a week or so ago.

**Comment by NetOperatorWibby** [comment]
- On tipping, change "Resolve" button to "Tip"
- Change loading text on tipping example
- Explain with a sentence what is about to happen
