### ISSUE TITLE
Decide where links to pages should live.

### ISSUE THREAD

**Issue by jamesbiller** [lbryio/lbry.tech#138]
We need to decide how much cross-site linking we should be doing between .io and .tech

**Comment by NetOperatorWibby** [comment]
@alyssaoc I don't think this applies to me.

**Comment by alyssaoc** [comment]
Issue moved to [lbryio/growth #86](https://github.com/lbryio/growth/issues/86) via [**ZenHub**](https://www.zenhub.com/)
