### ISSUE TITLE
Generate API examples for .tech

### ISSUE THREAD

**Issue by alyssaoc** [lbryio/lbry.tech#139]
As a user of the https://lbry.tech/resources api pages, I would like to see examples from the api call on the page.

@tzarebczan  Please take a look and see how best to break this up, after vacation

**Comment by tzarebczan** [comment]
Those examples should be on the api pages themselves, which would come from the same place that the api data does (I think?). Some of them would also be covered in the tour.

**Comment by NetOperatorWibby** [comment]
Yeah, the resources page is not the place for examples. The right side of entries on the API pages need examples: https://lbry.tech/api/protocol

**Comment by alyssaoc** [comment]
@tzarebczan and @NetOperatorWibby Yes sorry, I went up a level because we need them for both blockchain and protocol

**Comment by lyoshenka** [comment]
can't have "ready for work" and "needs: grooming" at the same time

**Comment by tzarebczan** [comment]
The examples should come from the generated docs, so on each report.

lbrynet: https://github.com/lbryio/lbry/issues/1334
lbrycrd: https://github.com/lbryio/lbrycrd/issues/219

**Comment by tzarebczan** [comment]
working with @eukreign to try to get an output sample before he has the script completed.

**Comment by tzarebczan** [comment]
@NetOperatorWibby - see https://gist.github.com/tzarebczan/1af2e79ba365a006d1b1f0079a3cb03c for the example output from the SDK team. "output": "(map) added account details" will be replaced later on via a script with an actual output that's run during unit tests. 

Hoping the blockchain team can do something similar: https://github.com/lbryio/lbrycrd/issues/219

**Comment by tzarebczan** [comment]
@NetOperatorWibby, no it's in a branch until he gets the concrete examples worked out. You can access it this way: https://github.com/lbryio/lbry/blob/095816781b9df1845340ef11efbc4090b1e0faf5/docs/api.json

**Comment by NetOperatorWibby** [comment]
I'd rather wait until this is in master. The last time I focused on a non-master branch it got deleted and no one told me, which lead to .tech crashing.

**Comment by tzarebczan** [comment]
Can you only include examples when that specific tag exists? We wanted to get this out with the output format so you can start working on it before a finished product is ready. Not sure where this fits in with the promotional campaign launch, but I'd rather this portion be ready when the examples tag exists in the api docs. Maybe @eukreign / @kauffj can comment further.

**Comment by NetOperatorWibby** [comment]
It's not insurmountable work. IMO, if it's not in master, it's not ready.

**Comment by tzarebczan** [comment]
Please verify that the format and appearance will work, not asking to go live with this. There are three different formats for calls, we'd eventually allow users to cycle through / select the one that best suites them. We can just use the lbrynet example as a first go around.

**Comment by kauffj** [comment]
@NetOperatorWibby please confirm that this format is acceptable by testing locally
