### ISSUE TITLE
tour times out and fails to load additional examples

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry.tech#143]
I've noticed this a few times already - if you run through step 1 and leave the page open for a while and then try to go to another step, or re-run the same one, the page will hang and require a refresh 

![image](https://user-images.githubusercontent.com/8120721/45903231-eea09900-bdb6-11e8-85d8-6b1faaea3f3b.png)

**Comment by NetOperatorWibby** [comment]
This occurs (...or, doesn't) because the WebSocket connection closes. I'll see if I can keep it open.

**Comment by NetOperatorWibby** [comment]
This even works across (local) server restarts. Interesting.

**Comment by NetOperatorWibby** [comment]
Closed via https://github.com/lbryio/lbry.tech/commit/e1cf4d960391a74c9f483f5e975c1f92ad25ce49
