### ISSUE TITLE
Unify or differentiate claimtrie resources

### ISSUE THREAD

**Issue by kauffj** [lbryio/lbry.tech#155]
https://lbry.tech/resources/claimtrie and https://lbry.tech/resources/lbry-claimtrie ought to be combined or more clearly differentiated in their title and purposes (as well as reference each other).

Both files are located in this folder: https://github.com/lbryio/lbry.tech/tree/master/documents/resources

**Comment by alyssaoc** [comment]
@BrannonKing please review and advise

**Comment by lyoshenka** [comment]
fixed by c672feb4aa00c0fd3eb20865aae962852aa9a726
