### ISSUE TITLE
Improve site metadata

### ISSUE THREAD

**Issue by kauffj** [lbryio/lbry.tech#157]
Currently, it is not possible for individual pages to set things like their title, description, or og:image.

It should be possible to set all metadata values from both custom views as well as markdown pages.

**Comment by NetOperatorWibby** [comment]
This works for custom views as well. Example:

```js
state.lbry = {
  description: "This is the API page for LBRY.tech",
  "og:image": "/assets/media/images/carlsagan2.jpg",
  "og:image:height": 300,
  "og:image:width": 400
};
```

I've left a commented-out example here: https://github.com/lbryio/lbry.tech/blob/master/app/views/api.js
