### ISSUE TITLE
.tech remaining items

### ISSUE THREAD

**Issue by alyssaoc** [lbryio/lbry.tech#158]
- [x] Differentiate between the before/after view when completing examples
- [x] Explain significance of the action
- [ ] Human-friendly URL in the tip example's URL bar

Show `lbry://name#claim_id` where `name` is the claim's name. This should be "cached" and referenced when `show result` is called.

**Comment by NetOperatorWibby** [comment]
_Message for self_
Tip example loads indefinitely

**Comment by NetOperatorWibby** [comment]
@kauffj ^

**Comment by kauffj** [comment]
@NetOperatorWibby it's true that you need an address or claim id when calling `wallet_send` (though maybe it should support full URLs *cough* @eukreign). But I don't understand why we can't show a more readable URL in the bar itself.

**Comment by NetOperatorWibby** [comment]
@kauffj Would it make sense to do that? Wouldn’t the end user expect to be able to use another human-readable name to tip?
