### ISSUE TITLE
Deterministic formatting (Prettier and ???)

### ISSUE THREAD

**Issue by kauffj** [lbryio/lbry.tech#165]
Code formatting should be handled either deterministically (e.g. Prettier) or by a linter and only in special-cases by human inspection.

This goes for SCSS as well.

**Comment by NetOperatorWibby** [comment]
Prettier and Sass Lint are in the repo now. I don't like how Prettier "fixes" Sass so I disabled it. Sass Lint will tell you what's wrong though.
