### ISSUE TITLE
Repository Standards linked in Contributing guide 404's

### ISSUE THREAD

**Issue by Leopere** [lbryio/lbry.tech#183]
https://lbry.tech/repository-standards 404's it should at least link to the current standards until we add it here.

**Comment by tzarebczan** [comment]
Fixed the link, it is on lbry.tech https://github.com/lbryio/lbry.tech/commit/a398c88c73c9281401b2c101eee0a380784147a6

**Comment by kauffj** [comment]
1) You're on vacation @tzarebczan!
2) You should know about this: https://github.com/lbryio/lbry.tech/commit/7e90e092d66222bf4442a8b5ddf610e42d09f673#diff-f0232f60c7ffc6eeb10080f4f1543f42
