### ISSUE TITLE
Dynamic page/resource architecture

### ISSUE THREAD

**Issue by kauffj** [lbryio/lbry.tech#20]
In addition to defined pages being editable via Markdown, it should also be possible to create a markdown file and have this correspond directly to resource pages.

For example, a markdown file saved at `content/resources/wallet-app-authentication.md` could correspond to and be served in a rendered form at lbry.tech/resources/wallet-app-authentication.

**Comment by Krisseck** [comment]
This now works, as described in [this comment](https://github.com/lbryio/lbry.tech/issues/19#issuecomment-383881742).

One limitation currently is that Vuepress creates files with extension .html, so if you make for example file resources/wallet-app-authentication.md, the corresponding url is resources/wallet-app-authentication.html
