### ISSUE TITLE
ssl redirection not occuring on lbry.tech

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry.tech#206]
Thanks to @Invariant-Change for spotting this one. If you open an incognito window and go to http://lbry.tech or lbry.tech, you are not redirected to the https site. @Invariant-Change mentioned that the cert shows beta.lbry.tech - not sure if that's related or not.

**Comment by NetOperatorWibby** [comment]
This is interesting. [`heroku-ssl-redirect`](https://github.com/lbryio/lbry.tech/blob/master/package.json#L32) is listed in the `package.json` but it's not referenced in the codebase. Does anyone know who issued the original cert in the first place?

**Comment by NetOperatorWibby** [comment]
@tzarebczan @Invariant-Change 

Can you guys ensure this works for you? I just pushed up a fix and it appears to work for me.

**Comment by tzarebczan** [comment]
Works for me, closing! The cert does show beta.lbry.tech but Niko said that's fine.
