### ISSUE TITLE
Bring back github LBC reward as part of quickstart

### ISSUE THREAD

**Issue by lyoshenka** [lbryio/lbry.tech#209]

**Comment by NetOperatorWibby** [comment]
@lyoshenka What did this look like before?

**Comment by tiger5226** [comment]
as a reference - https://github.com/lbryio/internal-apis/blob/e862dea962038e10bc2013462aea489416240a2c/app/model/user_social.go

**Comment by tiger5226** [comment]
The entry point was https://github.com/lbryio/internal-apis/blob/e862dea962038e10bc2013462aea489416240a2c/app/actions/shared.go

Basically, we allowed authentication via github which would allow them to claim the new developer reward. 

Are we still going that route as part of this?

**Comment by kauffj** [comment]
@NetOperatorWibby and I went over this in person on Friday. We're going to keep this to just GitHub right now. Since it's just going to be on lbry.tech, it won't really affect the app.

**Comment by tiger5226** [comment]
@NetOperatorWibby -  I have implemented a working version of the reward. It will still go through the review process, but you can at least have something to test against. Please the issue mentioned above for details.
