### ISSUE TITLE
Audit site for places to add whitepaper links

### ISSUE THREAD

**Issue by kauffj** [lbryio/lbry.tech#218]
In particular, the glossary contains many places that should now link to the specification.

**Comment by AdamZWinter** [comment]
Please see PR #226 on this.

**Comment by kauffj** [comment]
@tzarebczan are you happy with @AdamZWinter's work here or do you want to do your own pass?

Thanks for #226 @AdamZWinter !

**Comment by tzarebczan** [comment]
I'll take another pass at this sometime this week...

**Comment by lyoshenka** [comment]
fixed in https://github.com/lbryio/lbry.tech/pull/258
