### ISSUE TITLE
Interactive Component Overview Javascript/Style Changes

### ISSUE THREAD

**Issue by kauffj** [lbryio/lbry.tech#220]
I stripped this down a lot in #219. However, there's more to do:

- It is still confusing to navigate through submodules, both before and after opening them. 
  - Maybe we should just allow them to be clickable even before expanding a major area? (but keep them light / gray)
- The layout should match that of the primary modules.
  - Put the repo in the top right, as it is on the major modules.
  - Move "back to" to the bottom, below the content.

I still think this area has issues and could be overhauled further, but this is probably sufficient for release.

**Comment by tzarebczan** [comment]
I think we also need to separate out wallet server and client. If you go into wallet from data network, you see the following, which is incorrect  ```CONNECTION TO DATA NETWORK
wallet is an application built on top of the LBRY data network.``` 

It's referenced as wallet and wallet server.

**Comment by NetOperatorWibby** [comment]
Repo name in top right looks gross.

**Comment by kauffj** [comment]
I just want consistency. Right now the repos are in the top right on the main blocks and I don't like that the location flips.
