### ISSUE TITLE
schema doc should read from spec/repo

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry.tech#221]
https://lbry.tech/resources/schema should read from the lbryschema repo or redirect to spec

**Comment by lyoshenka** [comment]
it should read from https://github.com/lbryio/types/tree/master/proto

**Comment by lyoshenka** [comment]
or that section could be dropped completely and you could just link to the protobuf files.

**Comment by tzarebczan** [comment]
This was redirected to https://lbry.tech/spec#metadata
