### ISSUE TITLE
UX: Horizontal scrolling content is hard to read - collapsable right column?

### ISSUE THREAD

**Issue by jsigwart** [lbryio/lbry.tech#228]
I am trying to use lbry.tech. I have a fairly small screen. I'm trying to read what's in the bluish box in the center of the page, and the horizontal scroll bar is driving me nuts. I'd really like to be able to collapse the gray column on the right so that blue screen can fill the space and I could see everything.

<img width="1330" alt="screen shot 2019-01-21 at 3 21 45 pm" src="https://user-images.githubusercontent.com/1363664/51504198-91344d00-1d94-11e9-9580-d6b859b4b2b9.png">

**Comment by NetOperatorWibby** [comment]
This page is now responsive but it doesn't make sense to collapse the right column b/c it's a reference to what's on the left.
