### ISSUE TITLE
Update README and other documentation to follow standards

### ISSUE THREAD

**Issue by kauffj** [lbryio/lbry.tech#23]
Standards are [here](https://docs.google.com/document/d/1zBi8BifeRslhUPkDrb0lK4-OSjMPnkcNAxRduAwuvvo/edit).

If there are any pending technology or setup/environment choices, you can wait until those are made to do this.

**Comment by Krisseck** [comment]
Just updated these files, I made you @kauffj the contact person in README.

**Comment by kauffj** [comment]
@Krisseck acknowledged.
