### ISSUE TITLE
Fonts not loading (404)

### ISSUE THREAD

**Issue by Wick** [lbryio/lbry.tech#231]
I get 404 on all Inter UI fonts on all pages in the browsers i tested (firefox, chrome, edge).
This results in wrong fonts showing and some other side effects such as the header area becomes scrollable (swipeable) up and down and not just left and right for mobile devices.
Example url: https://lbry.tech/overview

![capture](https://user-images.githubusercontent.com/4238024/51619837-70552e80-1f31-11e9-97f7-6081cd1753e2.PNG)

**Comment by tzarebczan** [comment]
Hey @Wick, thanks for filing this! Can we send you [some appreciation](https://LBRY.io/faq/appreciation) for doing so? @netoperatorwibby any idea what might be causing this? I'm seeing the same locally.

**Comment by NetOperatorWibby** [comment]
I'll check it out

**Comment by NetOperatorWibby** [comment]
I think the problem is Heroku and git submodules. The font folder literally does not exist on the live site.

**Comment by NetOperatorWibby** [comment]
via https://devcenter.heroku.com/articles/git-submodules:

> Using submodules for builds on Heroku is only supported for builds triggered with git pushes. Builds created with the API do not resolve submodules. This is also the case for GitHub sync.

Well this is annoying.

**Comment by NetOperatorWibby** [comment]
via https://devcenter.heroku.com/articles/github-integration:

> GitHub repos that use submodules will generally not deploy correctly on Heroku. This is because GitHub does not include submodule contents when repo-content tarballs are generated.
