### ISSUE TITLE
Playground tipping error

### ISSUE THREAD

**Issue by jsigwart** [lbryio/lbry.tech#232]
I go to the Playground, select Example 3, Support.

I click on one of the videos, and immediately, it tips the creator and returns the correct result:
<img width="1252" alt="screen shot 2019-01-23 at 2 49 45 pm" src="https://user-images.githubusercontent.com/1363664/51642454-2f9fea00-1f1e-11e9-9291-1cd1ba5cdae6.png">

I thought I had to click the "tip" button, and when I did, I got this screen:
<img width="1199" alt="screen shot 2019-01-23 at 2 06 28 pm" src="https://user-images.githubusercontent.com/1363664/51642501-56f6b700-1f1e-11e9-918f-b77ca5dedf1e.png">

This is confusing because it says I tipped the user in the green box at the top, but the result says it failed. There is no easy way to go back and see the original successful result.

**Comment by kauffj** [comment]
@NetOperatorWibby I haven't looked into this, but please add this to the epic and/or label campaign blocker if we need to tackle this before the push.

**Comment by NetOperatorWibby** [comment]
The creator whitelist has not changed (to my knowledge). I'll check with Tom.

**Comment by tzarebczan** [comment]
The problem happens when you click tip again, after a video was already tipped. Need to disable the button after it's run.
