### ISSUE TITLE
Responsiveness audit + fixes

### ISSUE THREAD

**Issue by kauffj** [lbryio/lbry.tech#237]

**Comment by seanyesmunt** [comment]
Not sure if this should be in it's own issue or not, but the spec could use a little bit of love on mobile. 

- Menu button styling
- Ensuring the menu is actually hidden on phones, it looks like it's half visible on some mobile screens

**Comment by NetOperatorWibby** [comment]
Yeah, that should be a new issue since the spec is in an iframe.
