### ISSUE TITLE
Audit all pages for proper open graph and other SEO/social metadata

### ISSUE THREAD

**Issue by kauffj** [lbryio/lbry.tech#245]
#30 is closed but we need to do this again before launch.

**Comment by NetOperatorWibby** [comment]
Here's an example of custom metadata being set for JS pages: https://github.com/lbryio/lbry.tech/blob/master/app/views/spec.js#L15-L18

The text between the `---` sections in Markdown files is how you change the metadata: https://raw.githubusercontent.com/lbryio/lbry.tech/master/documents/resources.md

This is the file where the custom metadata gets found and rendered: https://github.com/lbryio/lbry.tech/blob/master/app/components/head.js#L19-L36
