### ISSUE TITLE
Serving pages without .html and idealized folder structure

### ISSUE THREAD

**Issue by kauffj** [lbryio/lbry.tech#25]
- [ ] All Markdown content is contained within a single folder (additional organization can exist within this folder, if necessary or desired, but it should not be necessary to call every file `index.md`). 
- [ ] All first-class pages as well as resource articles can be served by URLs that do not include a trailing `.html` or an indication of the folder structure. E.g. lbry.tech/repository-standards should serve the Markdown file located at `resources/repository-stanards.md`).

**Comment by Krisseck** [comment]
We are currently using Node.js + express. I tried implementing this but the internal links in Vuepress will not work with this.

[Here is the related issue on Vuepress repo.](https://github.com/vuejs/vuepress/issues/78)

So their solution this currently is that if you want to make for example page /resources, you can make resources/index.md, which will work. I would personally much rather have working rewrites though :)

**Comment by Krisseck** [comment]
I have now spent a day researching this, and I am afraid this is currently not possible.

It's easy to set express rewrite rules to remove .html extension from urls, but in addition Vuepress uses it's own Vue-router to handle internal links. It generates a router config object on startup and this cannot be dynamically changed later. And it doesn't seem to offer any way for plugins to modify it.

**Comment by kauffj** [comment]
So is the solution to source each article from a folder?

**Comment by kauffj** [comment]
@Krisseck this issue has been edited based on discussion on standup today. I know Vuepress may not make this that easy. If it's non-trivial to reach the ideal specified above, please let me know how close we can get.
