### ISSUE TITLE
Dynamically calculate scrollbar on /spec

### ISSUE THREAD

**Issue by kauffj** [lbryio/lbry.tech#250]
Currently, lbry.tech/spec is showing a double scrollbar: one for the iframe, and one for the site itself.

**Comment by NetOperatorWibby** [comment]
Closed via https://github.com/lbryio/lbry.tech/commit/241926c649435223919e84ab720df4bdd53742fb

**Comment by lyoshenka** [comment]
@NetOperatorWibby i think the real way to fix this is to fix my hacky css in app/views/spec.js. The iframe size should not be hardcoded as `<div style="width: 100%; height: calc(100vh - 4rem)">`. It should be styled using sass, with the height calculated based on the size of the nav bar.

**Comment by NetOperatorWibby** [comment]
Okay. The issue _is_ fixed though.

EDIT: I'll fix the styling soon.
