### ISSUE TITLE
Running site locally and visiting sdk docs continuously redirects

### ISSUE THREAD

**Issue by jessopb** [lbryio/lbry.tech#273]
Under resources:
Visiting blockchain apis works.
Visiting sdk apis causes continuous redirects.

Reproduce.
 - clone repo
 - npm i
 - npm run watch
 - wait for 8080 and sass to build
 - visit localhost:8080
 - click resources
 - click SDK APIs

**Comment by NetOperatorWibby** [comment]
The raw SDK link was pointing to a file in a branch that no longer exists. For the future, the API JSON files will only refer to the master branch. _That_ won't get deleted.
