### ISSUE TITLE
Better OG image

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry.tech#274]
Per @kauffj, we can improve on the OG image.

**Comment by NetOperatorWibby** [comment]
Would be nice to have specifics but I can come up with something.

**Comment by kauffj** [comment]
Audit the OG images of similar sites

**Comment by NetOperatorWibby** [comment]
They aren't good. Consensys and Lisk are terrible.

**Comment by kauffj** [comment]
And that's why we don't copy from blockchain companies :stuck_out_tongue: 

Although I did a quick check of Dart and ReactJS homepages, both just use their logos.

**Comment by NetOperatorWibby** [comment]
I'm confused as to what I'd be auditing then. Here are some screenshots:

![og-1](https://user-images.githubusercontent.com/1288356/56167817-d684a700-5f9e-11e9-93a5-585009ec28a3.png)
![og-2](https://user-images.githubusercontent.com/1288356/56167822-da182e00-5f9e-11e9-80ce-858587395b19.png)
![og-3](https://user-images.githubusercontent.com/1288356/56167827-de444b80-5f9e-11e9-8a22-799447733117.png)

**Comment by kauffj** [comment]
Well, we should audit like to like.

For lbry.tech, that's looking at sites that introduce technologies: languages, frameworks, etc. For these, it appears to be a lot of logos, which does make me wonder if we can do better by adding some text or additional info.

For lbry.com, that'd be looking at sites that host downloadable client software with similar user demos (Steam, Discord, uTorrent, etc.).

**Comment by NetOperatorWibby** [comment]
@kauffj Are these images okay?

**Comment by kauffj** [comment]
LGTM
