### ISSUE TITLE
Update to support new SDK

### ISSUE THREAD

**Issue by nikooo777** [lbryio/lbry.tech#278]
Lbry.tech should add support for the new SDK. That means changing the calls to the web daemon and adapting the examples to reflect the new metadata/calls

**Comment by NetOperatorWibby** [comment]
This should be broken into different issues. The examples are from the SDK and blockchain teams.

**Comment by tzarebczan** [comment]
Talking about the sdk itself...it includes new metadata and some api changes. See the last 2 set of release notes on https://github.com/lbryio/lbry/releases

**Comment by tzarebczan** [comment]
This was done for 0.37 support.
