### ISSUE TITLE
Hook: Actual publication on Step 2

### ISSUE THREAD

**Issue by Krisseck** [lbryio/lbry.tech#28]
The daemon requires the image to be a local file. How do we get the file uploaded to the daemon server, or is there another way to do this?

**Comment by kauffj** [comment]
Pending https://github.com/lbryio/web-daemon/issues/6

**Comment by Krisseck** [comment]
Also pending this: https://github.com/lbryio/lbry/pull/1238

**Comment by kauffj** [comment]
(There is nothing to actually do for lbry.tech, this ticket is just staying open until it's resolved by lbry release and we've confirmed we're done)

**Comment by Krisseck** [comment]
Daemon is now updated and publication works on the site.
