### ISSUE TITLE
Do something cool with tags and metadata

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry.tech#284]
Now that we have tags and other metadata, we should show it off on lbry.tech in someway

**Comment by NetOperatorWibby** [comment]
This is super open-ended. Why make an issue?

**Comment by tzarebczan** [comment]
Because it was a good idea and I'm sure you can come up with something creative.

**Comment by jsigwart** [comment]
Do we have hooks where a developer could call specific keywords to get a custom result? Make a custom app? Something with Chainquery? Do we have anything in lbry.tech that explains the new metadata? How would I go about learning about the new changes?
