### ISSUE TITLE
Set Social and Search Metadata

### ISSUE THREAD

**Issue by Krisseck** [lbryio/lbry.tech#30]
Metatags, Sitemap, etc.

**Comment by kauffj** [comment]
First task: figure out how site description meta tag as well as open graph images can be set in Markdown

**Comment by Krisseck** [comment]
@kauffj It's easy Vuepress documentation has the info: https://vuepress.vuejs.org/guide/markdown.html#front-matter

Basically, at the start of the markdown file you can do:
```
---
meta:
  - name: description
    content: Description goes here
  - property: og:image
    content: http://thisismyimage.com/image.jpg
---

**Comment by tzarebczan** [comment]
@kauffj is this subsumed by https://github.com/lbryio/lbry.tech/issues/92? Should I create a separate issue for the MD metatags?

I think @jsigwart and Stephen are looking into SEO.

**Comment by kauffj** [comment]
#92 is specifically related to header hierarchy on pages. This ticket should not be considered closed until all markdown files are reviewed and appropriate metadata is set.

**Comment by NetOperatorWibby** [comment]
Closed via https://github.com/lbryio/lbry.tech/commit/7654917466ae1bfdf25414862f2c29aa32763cc9
