### ISSUE TITLE
broken link on resources page

### ISSUE THREAD

**Issue by hamnox** [lbryio/lbry.tech#315]
[Page in question](https://github.com/lbryio/lbry.tech/blob/master/documents/resources.md)

The link to **lighthouse** is broken. I assume it's meant to link to a gh-page for the [repo](https://github.com/lbryio/lighthouse) but the url (lbryio.github.io/lighthouse) doesn't resolve and there's no gh-pages branch.

**Comment by kauffj** [comment]
Thank you @hamnox, fixed in https://github.com/lbryio/lbry.tech/commit/71d78c40d97c739350f20ea784d973c7aacf961a

If you'd like an LBC tip for this, please email an address to hello@lbry.com with a link to this comment
