### ISSUE TITLE
Contributor's Guide: Describe how to contribute to translations

### ISSUE THREAD

**Issue by Follpvosten** [lbryio/lbry.tech#316]
Hello!

I would personally like to contribute to the german translation of the lbry-desktop/lbry.tv, because I've noticed that the current ones are a bit lacking (they really sound like they're not written in a context-aware way, sometimes they even seem like auto-generated translations).

However, I can't find anything about contributing to translations - the Contributor's Guide lists information about coding, designing, writing (that's things like blog posts afaict), testing and raising issues, but I can't find anything about contributing localization/translations on the whole page. Would be great if something like that was added!

**Comment by kauffj** [comment]
Thanks @Follpvosten, I updated the contributing page, though the instructions need work.

Translations are managed by the LBRY community. It's primarily organized via the #translators room in a Discord chat (chat.lbry.org).

We use that room to discuss / meet potential translators, after which you can be added to the Transifex system.
