### ISSUE TITLE
lbrycrd no longer has a "master" branch

### ISSUE THREAD

**Issue by BrannonKing** [lbryio/lbry.tech#319]
It has a v12_master, v17_master, and v19_master. This is not playing nicely with api.js, which seems to expect a "master" branch. It should use the default branch on the repository if possible. It would be okay if it used the latest tag. It looks like it has code to get the latest tag but often falls back to tag[0], which is "master".

Duplicate of https://github.com/lbryio/lbrycrd/issues/388

**Comment by tzarebczan** [comment]
@kauffj do you think you can look at this one? A few people noticed it recently.

**Comment by BrannonKing** [comment]
Fixed with the reintroduction of the master branch.
