### ISSUE TITLE
Commit Feed

### ISSUE THREAD

**Issue by kauffj** [lbryio/lbry.tech#32]
It'd be cool if on the homepage or somewhere on the site there was just a feed of all of the commits happening at LBRY across all repos.

**Comment by Krisseck** [comment]
That would be fun! Couple of points:
- [Github seems to have this functionality in their API. ](https://developer.github.com/v3/activity/events/)
- How about the feed on private repos? Do we want to show that?
- We need some basic DB functionality on Heroku, we need to cache the feed content somewhere.

**Comment by kauffj** [comment]
- No private repos.
- Fine/good to add a DB. I think @lyoshenka prefers MySQL. This could probably also be done without a DB and just an in-memory cache like Redis.

**Comment by Krisseck** [comment]
The github feed is now live! http://beta.lbry.tech/github-feed.html It updates once a minute and caches the events to Redis.
