### ISSUE TITLE
Clarify installation requirement in developer-program

### ISSUE THREAD

**Issue by bilou1998** [lbryio/lbry.tech#337]
when claim in developer-program https://lbry.tech/developer-program  
https://github.com/lbryio/lbry.tech/edit/master/documents/developer-program.md

even if u have old github and + 10 commits 

still getting msg " the reward cannot be claimed without installation"  can some one fix it and Clarify what to install? ??

![Annotation 2021-02-05 014844](https://user-images.githubusercontent.com/74540263/107024706-aa0bd180-67a8-11eb-819f-46aa73a8c706.jpg)

**Comment by tzarebczan** [comment]
This is a bug and will be fixed soon, sorry about that!

**Comment by tzarebczan** [comment]
Try again now, it should work!
