### ISSUE TITLE
Sidebar functionality is missing

### ISSUE THREAD

**Issue by Krisseck** [lbryio/lbry.tech#37]
This functionality was removed on redesign, make sure it is implemented again or message if it's not needed.

There's already a Sidebar component ready in Components folder.

**Comment by NetOperatorWibby** [comment]
I'm not sure if this is still needed. I can definitely add it back if it appears to be necessary. I think when the docs are fleshed out, the importance of a sidebar will become apparent.

**Comment by kauffj** [comment]
Let's see how this works on glossary.

**Comment by kauffj** [comment]
Sidebar should be able to be toggled on or off with a metadata setting for the page.

**Comment by alyssaoc** [comment]
@tzarebczan Let me know if this should be assigned to someone else

**Comment by tzarebczan** [comment]
@alyssaoc most likely needs to be assigned to Paul.

**Comment by NetOperatorWibby** [comment]
@tzarebczan You can check out the glossary here: http://staging.lbry.tech/glossary

**Comment by tzarebczan** [comment]
@NetOperatorWibby Looks good to me and working as expected. Should we have a show/hide option?
