### ISSUE TITLE
Email collection

### ISSUE THREAD

**Issue by kauffj** [lbryio/lbry.tech#38]
I'd like there to be a component that supports email collection and adds them to our user database tagged "developer". I say component because I'm not sure exactly where on the site this will live.

Adding the user to our database is relatively simple. Just `POST` the values `email` and `tag=developer` to `api.lbry.io/list/subscribe`. You can see PHP example code here: https://github.com/lbryio/lbry.io/blob/master/lib/thirdparty/LBRY.class.php#L20.

**Comment by Krisseck** [comment]
For now, I added the email component to the footer of every page, this can be of course changed easily.
Subscribing does not work currently because the LBRY API endpoint does not have correct CORS headers. @kauffj, who can I ask about this?

**Comment by kauffj** [comment]
Filed here though you might not be able to see it https://github.com/lbryio/internal-apis/issues/336

Most likely @nikooo777 will tackle, but whoever does will let you know. Expected to be done this week.

**Comment by tiger5226** [comment]
@Krisseck The api-server should support CORS. This can be enabled I believe by making sure you are setting the `Origin` in the headers. 

https://github.com/lbryio/internal-apis/blob/master/app/actions/server.go#L70-L74

As long as its there it will allow it.

**Comment by tiger5226** [comment]
Perfect, nice find!! Let me know if you need anything else.
