### ISSUE TITLE
Is it possible to customize meta tags in Vuepress?

### ISSUE THREAD

**Issue by NetOperatorWibby** [lbryio/lbry.tech#41]
I want to add `<meta name='viewport' content='initial-scale=1, viewport-fit=cover'>` to the `<head/>` for iPhone X support. Reference here: https://webkit.org/blog/7929/designing-websites-for-iphone-x

This is low priority as I don't expect people to visit the site in landscape mode. _The rumored upcoming iPad will change this expectation though._

**Comment by Krisseck** [comment]
Sure, here is the documentation: https://vuepress.vuejs.org/config/#head
The file in question is .vuepress/config.js, I just made a commit that added meta tag you asked.

**Comment by NetOperatorWibby** [comment]
Good grief, I thought I searched thoroughly. Thanks man.
