### ISSUE TITLE
Add ability to display OpenAPI specified API signatures

### ISSUE THREAD

**Issue by kauffj** [lbryio/lbry.tech#49]
We will have at least two:

- lbry
- lbrycrd

For now, this functionality can be added with dummy spec files.

**Comment by NetOperatorWibby** [comment]
Did we ever discuss _where_ this was going to live?

**Comment by kauffj** [comment]
You can assume the file is accessible on local disk.

**Comment by NetOperatorWibby** [comment]
I should've written more descriptive notes to myself, I now remember this is to be a placeholder for now.
