### ISSUE TITLE
Overview Page

### ISSUE THREAD

**Issue by kauffj** [lbryio/lbry.tech#51]

**Comment by kauffj** [comment]
As discussed on our meeting today, we're giving some consideration as to whether this could be better done as a dynamic javascript component than a simple image. This approach would allow individual components of the stack to be expanded. 

It may also make sense to do this in a way that let's people iterate through the various components (e.g. the blockchain starts expanded, clicking an arrow or next expands the next component, etc., though it should absolutely be possible to click a component directly rather than stepping through).

**Comment by kauffj** [comment]
@NetOperatorWibby I encourage you to share ideas with me as you have them, or show me half-finished attempts, as I have a lot of ideas about this.

**Comment by kauffj** [comment]
Jeremy to fill in copy and provide any further feedback.

**Comment by kauffj** [comment]
@kauffj will push his changes today.

**Comment by NetOperatorWibby** [comment]
@kauffj In case you want to see this section as it's intended to look: http://staging.lbry.tech/overview

**Comment by kauffj** [comment]
Nice - I did push some copy changes to master yesterday if you want to rebase, though it's not urgent to do so

**Comment by alyssaoc** [comment]
@lyoshenka Is a review needed from you here?

**Comment by lyoshenka** [comment]
no, though ive looked at it some and will look at it some more
