### ISSUE TITLE
Dependency vulnerabilities

### ISSUE THREAD

**Issue by NetOperatorWibby** [lbryio/lbry.tech#53]
The affected dependencies in question are `node-sass` and `vuepress` due to _their_ dependencies. You can view this info yourself by running `npm i` → `npm shrinkwrap` → `npm audit`.

**Comment by NetOperatorWibby** [comment]
Found a fix for `node-sass`: https://github.com/sass/node-sass/issues/2288#issuecomment-384964399

**Comment by NetOperatorWibby** [comment]
Not sure if we want to this paid integration (or something similar) but it may help: https://github.com/marketplace/greenkeeper

**Comment by Krisseck** [comment]
Fixed the issue with `node-sass`, but vuepress/string vulnerability is still open, see here: https://github.com/vuejs/vuepress/issues/493

**Comment by Krisseck** [comment]
I had to revert the version of node-sass, it broke our build on Heroku.

**Comment by NetOperatorWibby** [comment]
Figured we'd be at the mercy of maintainers of those packages.
