### ISSUE TITLE
Standalone email collection page

### ISSUE THREAD

**Issue by kauffj** [lbryio/lbry.tech#64]
As an expansion of #38, I'd like there to be an extremely simple full page for developer email collection.

See https://lbry.io/list/subscribe as an example (but it could be event simpler).

This link should not be in any navigation.

This is so we have a link to use directly when we want to tell a developer how to join our mailing list.

**Comment by Krisseck** [comment]
The page: beta.lbry.tech/subscribe

**Comment by kauffj** [comment]
Re-opening this in favor of https://github.com/lbryio/growth/issues/192

(You cannot transfer that issue to this one since the repo is private)
