### ISSUE TITLE
Resource management

### ISSUE THREAD

**Issue by kauffj** [lbryio/lbry.tech#72]
This issue depends on the resolution of #25, but presumably there will eventually be a folder somewhere that contains a large number of resource documents created in Markdown.

To go along with this, we'd want a component that dumps all of these out, or lists/categorizes them in some way.

**Comment by NetOperatorWibby** [comment]
All resource documents will be available at the root on .tech, so contributers won't have to search for them. https://github.com/lbryio/lbry.tech/tree/new/documents
