### ISSUE TITLE
URLs, Name Resolution

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry.tech#81]
Breaking out article topics from: https://github.com/lbryio/lbry.tech/issues/31#issuecomment-393218343

@kauffj who should we assign this one to?

**Comment by kauffj** [comment]
Existing resources:

http://lbry.io/faq/naming
https://lbry.io/faq/claimtrie-implementation

Candidates are: @lyoshenka @eukreign @jackrobison and me

**Comment by lyoshenka** [comment]
the spec will cover this in detail
