### ISSUE TITLE
Using lbrynet as a library in your code

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry.tech#85]
Breaking out article topics from: https://github.com/lbryio/lbry.tech/issues/31#issuecomment-393218343

@kauffj who should we assign this one to?

**Comment by hackrush01** [comment]
Something I wrote up a while ago: https://github.com/lbryio/lbry.io/pull/191/files

**Comment by kauffj** [comment]
^ Above content should probably be moved to lbry.tech

(If moving, make sure to 301 redirect the old URL)

**Comment by hackrush01** [comment]
The old one never made it to production as it was language specific
But we can still add it to lbry.tech

**Comment by kauffj** [comment]
@hackrush01 if it's still valid, can you submit it as a PR to lbry.tech? Just create a markdown file in the resources folder

**Comment by hackrush01** [comment]
Ok, I'll look into it soon after catching up with my current issues

**Comment by tzarebczan** [comment]
@hackrush01 would this suffice for the issue discussed at the full team meeting?

**Comment by hackrush01** [comment]
@tzarebczan Yes.
