### ISSUE TITLE
Remove Slack,  update Discord URL, add StackOverflow?

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry.tech#88]
The Discord URL is actually https://chat.lbry.io and we should remove Slack (currently pointed to chat.lbry.io) as it's only an internal team tool. 

@kauffj are we ready to add SO as a dev resource? Maybe a link to https://stackoverflow.com/questions/tagged/lbry ?

**Comment by kauffj** [comment]
No, we are not.

Filed https://github.com/lbryio/lbry.tech/issues/89 to encourage us to make a call.

**Comment by NetOperatorWibby** [comment]
Added a new issue to keep track of the developer resource.
