### ISSUE TITLE
Overview Mission Styling

### ISSUE THREAD

**Issue by kauffj** [lbryio/lbry.tech#95]
Two small changes to further styling of the Mission part of the Overview page:

- Add actual styling for the pull-quote / mission statement.
- Improve styling of the stack of `<sup>` tags

(Alternatively, tell me you hate this approach stylistically ;) )

**Comment by kauffj** [comment]
I don't think the existing blockquote styling works well for this. I'd prefer something that both reduces the width and gives even more emphasis.

**Comment by NetOperatorWibby** [comment]
Closed via https://github.com/lbryio/lbry.tech/commit/7cca6711c5b3ce61795f4b6c140d4a473c38fb8f
