### ISSUE TITLE
Continued Ecosystem Component Improvements

### ISSUE THREAD

**Issue by kauffj** [lbryio/lbry.tech#96]
Please discuss this ticket with my synchronously, some of this information is better verbally communicated/explained rather than written:

- [ ] Improve communication of how auxiliary components interact with core components
- [ ] Allow auxiliary components to be clicked
- [ ] Add statefulness to the overview (if I expand an area, click a link, and click back, I should be back where I was)
- [ ] "First class" display of repos

**Comment by NetOperatorWibby** [comment]
@kau

**Comment by NetOperatorWibby** [comment]
@kauffj Do you still need those components clickable? Or is hover fine?

**Comment by kauffj** [comment]
@kauffj needs to give feedback on this.

**Comment by kauffj** [comment]
I think this is pretty much there. Some notes:

- The auxiliary components show a vertical scrollbar when expanded - intended? If the intent was to keep the height the same as the 3-block stack, they're different heights as well.
- Can we try labeling the auxiliary components in the same light gray of the circle prior to expanding one of the 3 blocks? Can we also allow them to be clicked prior to expanding?
