### ISSUE TITLE
Wiki/Glossary/Resource Linking Syntax

### ISSUE THREAD

**Issue by kauffj** [lbryio/lbry.tech#97]
I started putting `[[` and `]]` around key terms when creating copy as an experiment (currently only in Overview). The idea is when a term appears in these brackets, it would:

- Link to a full resource page, if one exists
- Link to a deterministic glossary URL (e.g. lbry.tech/glossary#term) if it doesn't

Possibly only the latter (glossary links) are necessary.

**Comment by Krisseck** [comment]
I installed [markdown-it-wikilinks](https://www.npmjs.com/package/markdown-it-wikilinks) on the site.

> Link to a deterministic glossary URL (e.g. lbry.tech/glossary#term) if it doesn't

This part was easily done, so now every time you make `[[something]]` link it goes to glossary.html#something. For testing, there's a blockchain link here: https://lbry.tech/community/
And it links to the basic glossary page I did: https://lbry.tech/glossary.html#blockchain

> Link to a full resource page, if one exists

This is bit hard to do using this package, I would suggest just using simple link tags, or link to glossary, then have a link there like "See page 'something' for more information"

**Comment by kauffj** [comment]
Looks good to me.
